---
title: "01_In-Class_Activity-01"
author: "Andrew-Gotshall"
date: '2023-01-26'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading_helpers}
source("Helper_functions.R")
fetchgender()
```


## First in-class activity on R objects. 

#### Question: 1 
```{r chunk1, echo = F}
gender <- factor(c("M", "F"), labels = c("Male", "Female"))
print("Gender variable before calling function")
print("----------------------------------------")
print(gender)
print("----------------------------------------")
print("Gender variable After calling function")
print("----------------------------------------")
# Call the function fetch_gender and print it 
gender <- fetchgender()
print(gender)
```


#### Question: 2
```{r chunk2}
# Vector 1 - Create a numeric vector of length 5 with the course ids 101, 255, 355, 461, 491
# Vector 2 - Create a character character vector of length 5 and provide the course titles for these 5 courses as, "Software Applications", "Introduction to OTM", "Decision Modeling and Analytics", "R Programming for Business and Analytics", "Intro to Text Analytics".
# Vector 3 - Create a first day of class vector (Make sure that this vector is a date vectors)
# Vector 4 - Create a start time vector (Make sure that this vector is a time vectors)
# Include date and time e.g., "2023-01-16 14:10:00"
# Vector 5 - Create a end time vector (Make sure that this vector is a time vectors)
# Vector 6 - Create a class frequency vector (a numerical vector, 1 represents the class meets once a week, 2 represents the class meets twice a week, etc.)
# Vector 7 - Create a class frequency character vector (R for Thursday, MWF for Monday-Wednesday-Friday class etc)
# Create a data frame using these above vectors

vector1 <- c(101, 255, 355, 461, 491)
vector2 <- c("Software Applications",
             "Introduction to OTM", 
             "Decision Modeling and Analytics",
             "R Programming for Business and Analytics",
             "Intro to Text Analytics")
vector3 <- c("2023-01-16", "2023-01-17","2023-01-18", "2023-01-16",
             "2023-01-17")
vector3 <- as.Date(vector3)
vector4 <- c("2023-01-16 14:10:00", "2023-01-17 17:10:00",
             "2023-01-18 19:10:00", "2023-01-16 20:35:00",
             "2023-01-17 18:25:50")
vector5 <- c("2023-01-16 16:25:00", "2023-01-17 19:10:00",
             "2023-01-18 20:10:00", "2023-01-16 21:35:00",
             "2023-01-17 20:25:50")
vector6 <- c(1L, 2L, 1L, 1L, 2L )
vector7 <- c("R", "MWF", "TR", "W", "TR")

library(lubridate)
start_date <- "2023-01-16"
start_date <- "01162203"
mdy(start_date)
class(ymd(start_date))

df1 <- data.frame(vector1, vector2, vector3, vector4, vector5, vector6, vector7)
head(df1)

View(df1)

df1$vector3 <- as.Date(df1$vector3)
str(df1)
```

#### Question: 3
```{r}
# Create a function to read the first day of class as string and the class frequency to return the next day of the class in the week. 
# Implement switch case instead of a sequence of if-else statements 

next_class <- function(start_day_of_class, frequency_of_class) {
  next_day_of_class <- switch(frequency_of_class,
                              "M" = start_day_of_class + 7,
                              "TR" = start_day_of_class + 2,
                              "TF" = start_day_of_class + 3)
  next_day_of_class                            
}

next_class(as.Date("2023-01-16"), "M")

df1$next_day_of_class <- next_class(df1$vector3, df1$vector7)

# having error with switch case...

for (i in 1:nrow(df1)) {
  df1[i, "next_day_of_class"] <- next_class(df1[i, 3], df1[i, 7])
}



```


