# Reading HW1.csv into global environment and creating a data frame
HW1 <- paste(getwd(), "/Input/",
                   "HW1.csv",
                   sep = "")
read.csv(HW1)
dfHW1 <- read.csv(HW1)

# Question 1: Using the data frame generated by reading the CSV file

library(lubridate)
dfHW1$End_Time <- ymd_hm(dfHW1$End_Time)
dfHW1$Start_Time <- ymd_hm(dfHW1$Start_Time)
dfHW1$duration <- difftime(dfHW1$End_Time, dfHW1$Start_Time,
         units = c( "mins"))


# Question 2: Create a new column in the same data frame as "late start"
# to store the logical output "TRUE"/"FALSE

dfHW1$late_start<- 0


start_date <- round_date(
  as.Date("2023-01-16"),
  unit = "week",
  week_start = getOption("lubridate.week.start", 2)
)

numeric_day <- function(class_frequency) {
  n_day <- switch(class_frequency,
         "M" = 1,
         "T" = 2,
         "MWF" = 1,
         "TF" = 2,
         "TR" = 2,
         "W" = 3,
         "R" = 4,
         "F" = 5)
  n_day
}

numeric_day("F")

dfHW1$numeric_day <- 0

for (i in 1:nrow(dfHW1)) {
  dfHW1[i, "numeric_day"] = numeric_day(dfHW1[i, "Class_Frequency"])
}






dfHW1$late_start <- ifelse(dfHW1$Start_Date == start_date, 
                           "False", "True")


# Question 3 Determine if there are discrepancies between the class start
# date and the class frequency.


# Question 4

extract_class_schedule <- function(class_time=0, 
                                   before_after = 0,
                                   class_frequency = 0) {
  if ( (class_time != 0) && (before_after != 0)) {
    if(before_after == "after"){ 
      df2 <- df1[hour(df1[, "Start_Time"]) > class_time,]
    } else if (before_after == "before") {
      df2 <- df1[hour(df1[, "Start_Time"]) <= class_time,]
    }
  } 
  df2
}
df3 <- extract_class_schedule(class_time = 12, 
                              before_after = "after")    
    
#question 5

overlapping_classes <- function(row_idx) {
  overlap_class_list <- c()
  for (i in 1:nrow(dfHW1)) {
    if (i == row_idx) {
      next
    } else {
      class1_start_time <- dfHW1[i, "Start_Time"]
      class1_end_time <- class1_start_time + minutes(df1HW1[i, "duration"])
      class2_start_time <- dfHW1[]
      if (difftime(class1_end_time, class2_end_time, units = "mins") < 0) {
        append(overlap_class_list, dfHW1[i, "Course_Id"])
        }
      }
  }
  list(overlap_class_list)
}











